name: ML-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.10
  - ipython=2.30.2
  - scikit-learn=1.0.2
  - dvc
  - pandas=1.2.3
  - numpy=1.22.2
  - pytest
  - jupyter=4.8.0
  - jupyterlab=3.0.10
  - fastapi=0.73
  - git=2.30.2