name: ML-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.10
  - ipython==7.21.0
  - scikit-learn==1.0.2
  - dvc=2.9.3
  - pandas==1.2.3
  - numpy==1.22.2
  - pytest
  - jupyter
  - jupyterlab==3.0.10
  - fastapi==0.63.0
  - git=2.30.2
  - uvicorn
  - gunicorn
  - hydra-core=1.0.6
  - mlflow=1.14.1
  - pip=20.3.3
  - pip:
      - wandb-0.10.31
      - zipp
